title: "Homesite of Prof S B Lisesivdin, PhD"
remote_theme: thelehhman/plainwhite-jekyll
show_excerpts: true

plainwhite:
  name: Prof Sefer Bora Lisesivdin
  tagline: "BSc, MSc, PhD, SMIEEE"
  date_format: "%b %-d, %Y"
  analytics_id: "UA-156556149-1"
  social_links:
    github: sblisesivdin
    linkedIn: "in/sblisesivdin" # format: locale/username
#  navigation:
#    - title: About
#      url: "/about.html"
#    - title: Other
#      url: "/other.html"
#    - title: Research
#      url: "/research.html"
#    - title: Publications
#      url: "/publications.html"
#    - title: Workbench
#      url: "/workbench.html"
  header_pages:
    - about.md
    - other.md
    - research.md
    - publications.md
    - workbench.md