title: Assoc Prof Dr S B Lisesivdin
description: >
  BSc (Eng), MSc, PhD, SMIEEE
   Department of Physics, Gazi University, Ankara, Turkey 06500
  bora@gazi.edu.tr
   +90 312 202 1391
  sblisesivdin.lrgresearch.org
theme: jekyll-theme-minimal
