title: Assoc Prof Dr S B Lisesivdin
description: BSc(Eng), MSc, PhD, SMIEEE
(1) Department of Physics, Gazi University, Ankara, Turkey 06500

Phone: +90 312 202 1391

bora@gazi.edu.tr

http://sblisesivdin.lrgresearch.org

theme: jekyll-theme-minimal
