title: Assoc. Prof. Dr. Sefer Bora Lisesivdin
author: S. B. Lisesivdin
email: sblisesivdin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
- CONTACT INFORMATION
-
- (1) Department of Physics, Gazi University, Ankara, Turkey 06500
- Phone: +90 312 202 1391
- Laboratory: Lab. Building Room 325
- Office: Dean Building Room 329
-  
-github_username:  sblisesivdin

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
exclude:
  - Gemfile
  - Gemfile.lock
