# Site settings
title: Sefer Bora Lisesivdin
tag_text: Homepage of Dr. Sefer Bora Lisesivdin
description: Professor of Physics, PhD, SMIEEE
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://sblisesivdin.github.io" # the base hostname & protocol for your site, e.g. http://example.com

plugins:
  - jekyll-seo-tag

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
